### ISSUE TITLE
Add a Makefile to simplify the execution of tests, styling, and other Bash commands.

### ISSUE THREAD

**Issue by truskovskiyk** [georgian-io/LLM-Finetuning-Toolkit#105]
Ensure that we include a Makefile containing all the necessary development commands, such as how to run tests, perform releases, and execute style checks, among others.

For a great example, see the Makefile at: https://github.com/huggingface/transformers/blob/main/Makefile

**Comment by benjaminye** [comment]
**Implementation Status**
- [x] Build
- [x] Publish to PyPI
- [ ] Run Tests
- [ ] Run Styling

**Comment by benjaminye** [comment]
this is implemented as of June 24, 2024
