### ISSUE TITLE
Add code coverage report for each PR, block PRs if coverage decreases

### ISSUE THREAD

**Issue by truskovskiyk** [georgian-io/LLM-Finetuning-Toolkit#107]
Reference: 

https://coverage.readthedocs.io/en/7.4.4/
https://pypi.org/project/pytest-cov/

https://github.com/marketplace/actions/code-coverage-summary
https://github.com/marketplace/actions/code-coverage-report-difference

**Comment by benjaminye** [comment]
Addressed in https://github.com/georgian-io/LLM-Finetuning-Toolkit/pull/184

- Set a hard floor of 80%
