### ISSUE TITLE
Add comment to indicate tf32 won't be available for older GPUs

### ISSUE THREAD

**Issue by angeliney** [georgian-io/LLM-Finetuning-Toolkit#134]
**Describe the bug**
I'm trying to run this toolkit on colab notebook with T4 GPU and ran into errors. In order to get it working, I needed to turn bf16 and tf32 to false, and fp16 to true. There's already a note for the bf16 and fp16, maybe we can add a note for tf32 as well.

**Comment by benjaminye** [comment]
Will do!
