### ISSUE TITLE
`pipx` installation doesn't work

### ISSUE THREAD

**Issue by angeliney** [georgian-io/LLM-Finetuning-Toolkit#135]
**Describe the bug**
Having trouble to install with `pipx`

**To Reproduce**
1. brew install pipx
2. pipx install llm-toolkit

**Expected behavior**
Installs fine

**Screenshots**
<img width="1440" alt="Screenshot 2024-04-08 at 11 35 41 AM" src="https://github.com/georgian-io/LLM-Finetuning-Toolkit/assets/15067864/d534c4f4-83c3-4386-82c7-6020e250b35c">

**Environment:**
 - OS: MacOS

**Comment by benjaminye** [comment]
This should be fixed now! Let me know if you run into this again.
