### ISSUE TITLE
Quickstart Basic uses a very large model and is slow.

### ISSUE THREAD

**Issue by SinclairHudson** [georgian-io/LLM-Finetuning-Toolkit#155]
The basic "quickstart" example downloads Mistral-7B-Instruct-v0.2, which is ~15GB, taking me over 20 minutes to download. A smaller model should be used as a quickstart example.

**To Reproduce**
1. Follow the "basic" level of quickstart

The basic version of the quickstart should be, in my opinion, a 10 minute (max) process and not require so much disk space.

**Environment:**
 - OS: Ubuntu 22.04
 - Packages Installed

**Comment by benjaminye** [comment]
Closed as this is fixed 😄!
