### ISSUE TITLE
Trying to access gated repo error, Quickstart Basic

### ISSUE THREAD

**Issue by richardehughes** [georgian-io/LLM-Finetuning-Toolkit#158]
After installation, run:
    llmtune generate config
       ==> works fine
    llmtune run ./config.yml
       ==> get this error

OSError: You are trying to access a gated repo.
Make sure to request access at https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2 and pass a token having permission to this repo either by logging in with `huggingface-cli 
login` or by passing `token=<your_token>`.

So then I do:    
     huggingface-cli login
         ===> login successfully
     llmtune run ./config.yml
       ==> get same error

Any ideas?

**Comment by benjaminye** [comment]
Hi @richardehughes, seems like Mistral has put an acknowledgement that you need to agree to before being able to download the weights. You need to go to: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2 and click agree. Then you can proceed as usual!

**Comment by richardehughes** [comment]
That worked!   Thanks so much!
