### ISSUE TITLE
example config file to run inference only on fine-tuned model

### ISSUE THREAD

**Issue by richardehughes** [georgian-io/LLM-Finetuning-Toolkit#160]
Is it possible to provide a config file that shows how to run inference on an already fine-tuned model?  

I have run the starter config, and it looks like the final PEFT model weights are in experiment/XXX/weights/.

So how do I re-run inference only (and possibly qa checks) on that model?

**Comment by benjaminye** [comment]
Closed due to inactivity. Please let us know if you require further assistance.

Please refer to issue https://github.com/georgian-io/LLM-Finetuning-Toolkit/issues/161 for any update for this feature request.
