### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2264' in position in command prompt

### ISSUE THREAD

**Issue by jeetendraabvv** [georgian-io/LLM-Finetuning-Toolkit#175]
Generating on test set: 25/25
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ prompt                               ┃ ground truth                          ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Below is an instruction that         │ The language of the text "Buonasera,  │
│ describes a task.  Write a response  │ il mio nome e Giuseppe" is Italian.   │
│ that appropriately completes the     │                                       │
│ request.  ### Instruction: Identify  │                                       │
│ the language of the text "Buonasera, │                                       │
│ il mio nome e Giuseppe." ### Input:  │                                       │
│ ### Output:                          │                                       │
└──────────────────────────────────────┴───────────────────────────────────────┘
Prediction >
  ### Output:  ### Input:  ### Output:  ### Input:  ### Input:  ### Output:  ###
Output:  ### Output:  ### Output:  ### Output:  ### Output:  ### Output:  ###
Output:  ### Output:  ### Output:  ### Output:  ### Output:  ### Output:  ###
Output:  ### Output:  ### Output:  ### Output:  ### Output:  ### Output:  ###
Output:  ### Output:  ### Output:  ### Output:  ### Output:  ### Output:  ###
Output:  ### Output:  ### Output:  ### Output:  ### Output:  ### Output:  ###
Output:  ### Output:  ### Output:  ### Output:  ### Output:  ### Output:  ###
Output:  ### Output:  ### Output:  ### Output:  ### Output:  ### Output:  ###
Output:  ### Output:  ### Output:  ### Output:  ### Output:  ### Output:  ###
Output:  ### Output:  ### Output:  ### Output:  ### Output:  ### Output:  ###
Output:  ### Output:  ### Output:  ### Output:
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ C:\ProgramData\anaconda3\envs\llm_tkit\Lib\site-packages\llmtune\cli\toolkit │
│ .py:122 in run                                                               │
│                                                                              │
│   119 │   │   │   config = yaml.safe_load(file)                              │
│   120 │   │   │   config = Config(**config)                                  │
│   121 │   │                                                                  │
│ ❱ 122 │   │   run_one_experiment(config, config_path)                        │
│   123                                                                        │
│   124                                                                        │
│   125 @generate_app.command("config")                                        │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │      config = Config(                                                    │ │
│ │               │   save_dir='./experiment/',                              │ │
│ │               │   ablation=AblationConfig(                               │ │
│ │               │   │   use_ablate=False,                                  │ │
│ │               │   │   study_name='ablation'                              │ │
│ │               │   ),                                                     │ │
│ │               │   data=DataConfig(                                       │ │
│ │               │   │   file_type='huggingface',                           │ │
│ │               │   │   path='yahma/alpaca-cleaned',                       │ │
│ │               │   │   prompt='Below is an instruction that describes a   │ │
│ │               task.  Write a response that appropriat'+89,               │ │
│ │               │   │   prompt_stub='{output}',                            │ │
│ │               │   │   train_size=500,                                    │ │
│ │               │   │   test_size=25,                                      │ │
│ │               │   │   train_test_split_seed=42                           │ │
│ │               │   ),                                                     │ │
│ │               │   model=ModelConfig(                                     │ │
│ │               │   │   hf_model_ckpt='facebook/opt-125m',                 │ │
│ │               │   │   device_map='auto',                                 │ │
│ │               │   │   torch_dtype='bfloat16',                            │ │
│ │               │   │   attn_implementation=None,                          │ │
│ │               │   │   quantize=True,                                     │ │
│ │               │   │   bitsandbytes=BitsAndBytesConfig(                   │ │
│ │               │   │   │   load_in_8bit=False,                            │ │
│ │               │   │   │   llm_int8_threshold=6.0,                        │ │
│ │               │   │   │   llm_int8_skip_modules=None,                    │ │
│ │               │   │   │   llm_int8_enable_fp32_cpu_offload=False,        │ │
│ │               │   │   │   llm_int8_has_fp16_weight=False,                │ │
│ │               │   │   │   load_in_4bit=True,                             │ │
│ │               │   │   │   bnb_4bit_compute_dtype='bfloat16',             │ │
│ │               │   │   │   bnb_4bit_quant_type='nf4',                     │ │
│ │               │   │   │   bnb_4bit_use_double_quant=True                 │ │
│ │               │   │   )                                                  │ │
│ │               │   ),                                                     │ │
│ │               │   lora=LoraConfig(                                       │ │
│ │               │   │   r=32,                                              │ │
│ │               │   │   task_type='CAUSAL_LM',                             │ │
│ │               │   │   lora_alpha=64,                                     │ │
│ │               │   │   bias='none',                                       │ │
│ │               │   │   lora_dropout=0.1,                                  │ │
│ │               │   │   target_modules='all-linear',                       │ │
│ │               │   │   fan_in_fan_out=False,                              │ │
│ │               │   │   modules_to_save=None,                              │ │
│ │               │   │   layers_to_transform=None,                          │ │
│ │               │   │   layers_pattern=None                                │ │
│ │               │   ),                                                     │ │
│ │               │   training=TrainingConfig(                               │ │
│ │               │   │   training_args=TrainingArgs(                        │ │
│ │               │   │   │   num_train_epochs=1,                            │ │
│ │               │   │   │   per_device_train_batch_size=4,                 │ │
│ │               │   │   │   gradient_accumulation_steps=4,                 │ │
│ │               │   │   │   gradient_checkpointing=True,                   │ │
│ │               │   │   │   optim='paged_adamw_32bit',                     │ │
│ │               │   │   │   logging_steps=1,                               │ │
│ │               │   │   │   learning_rate=0.0002,                          │ │
│ │               │   │   │   bf16=True,                                     │ │
│ │               │   │   ���   tf32=True,                                     │ │
│ │               │   │   │   fp16=False,                                    │ │
│ │               │   │   │   max_grad_norm=0.3,                             │ │
│ │               │   │   │   warmup_ratio=0.03,                             │ │
│ │               │   │   │   lr_scheduler_type='constant',                  │ │
│ │               │   │   │   save_steps=500                                 │ │
│ │               │   │   ),                                                 │ │
│ │               │   │   sft_args=SftArgs(                                  │ │
│ │               │   │   │   max_seq_length=1024,                           │ │
│ │               │   │   │   neftune_noise_alpha=None                       │ │
│ │               │   │   )                                                  │ │
│ │               │   ),                                                     │ │
│ │               │   inference=InferenceConfig(                             │ │
│ │               │   │   max_length=None,                                   │ │
│ │               │   │   max_new_tokens=256,                                │ │
│ │               │   │   min_length=0,                                      │ │
│ │               │   │   min_new_tokens=None,                               │ │
│ │               │   │   early_stopping=False,                              │ │
│ │               │   │   max_time=None,                                     │ │
│ │               │   │   do_sample=True,                                    │ │
│ │               │   │   num_beams=1,                                       │ │
│ │               │   │   num_beam_groups=1,                                 │ │
│ │               │   │   penalty_alpha=None,                                │ │
│ │               │   │   use_cache=True,                                    │ │
│ │               │   │   temperature=0.8,                                   │ │
│ │               │   │   top_k=50,                                          │ │
│ │               │   │   top_p=0.9,                                         │ │
│ │               │   │   typical_p=1.0,                                     │ │
│ │               │   │   epsilon_cutoff=0.0,                                │ │
│ │               │   │   eta_cutoff=0.0,                                    │ │
│ │               │   │   diversity_penalty=0.0,                             │ │
│ │               │   │   repetition_penalty=1.0,                            │ │
│ │               │   │   encoder_repetition_penalty=1.0,                    │ │
│ │               │   │   length_penalty=1.0,                                │ │
│ │               │   │   no_repeat_ngram_size=0,                            │ │
│ │               │   │   bad_words_ids=None,                                │ │
│ │               │   │   force_words_ids=None,                              │ │
│ │               │   │   renormalize_logits=False                           │ │
│ │               │   ),                                                     │ │
│ │               │   qa=QaConfig(                                           │ │
│ │               │   │   llm_tests=[                                        │ │
│ │               │   │   │   'jaccard_similarity',                          │ │
│ │               │   │   │   'dot_product',                                 │ │
│ │               │   │   │   'rouge_score',                                 │ │
│ │               │   │   │   'word_overlap',                                │ │
│ │               │   │   │   'verb_percent',                                │ │
│ │               │   │   │   'adjective_percent',                           │ │
│ │               │   │   │   'noun_percent',                                │ │
│ │               │   │   │   'summary_length'                               │ │
│ │               │   │   ]                                                  │ │
│ │               │   )                                                      │ │
│ │               )                                                          │ │
│ │ config_path = './config.yml'                                             │ │
│ │     configs = [                                                          │ │
│ │               │   {                                                      │ │
│ │               │   │   'save_dir': './experiment/',                       │ │
│ │               │   │   'ablation': {'use_ablate': False},                 │ │
│ │               │   │   'data': {                                          │ │
│ │               │   │   │   'file_type': 'huggingface',                    │ │
│ │               │   │   │   'path': 'yahma/alpaca-cleaned',                │ │
│ │               │   │   │   'prompt': 'Below is an instruction that        │ │
│ │               describes a task.  Write a response that appropriat'+89,   │ │
│ │               │   │   │   'prompt_stub': '{output}',                     │ │
│ │               │   │   │   'test_size': 25,                               │ │
│ │               │   │   │   'train_size': 500,                             │ │
│ │               │   │   │   'train_test_split_seed': 42                    │ │
│ │               │   │   },                                                 │ │
│ │               │   │   'model': {                                         │ │
│ │               │   │   │   'hf_model_ckpt': 'facebook/opt-125m',          │ │
│ │               │   │   │   'torch_dtype': 'bfloat16',                     │ │
│ │               │   │   │   'quantize': True,                              │ │
│ │               │   │   │   'bitsandbytes': {                              │ │
│ │               │   │   │   │   'load_in_4bit': True,                      │ │
│ │               │   │   │   │   'bnb_4bit_compute_dtype': 'bfloat16',      │ │
│ │               │   │   │   │   'bnb_4bit_quant_type': 'nf4'               │ │
│ │               │   │   │   }                                              │ │
│ │               │   │   },                                                 │ │
│ │               │   │   'lora': {                                          │ │
│ │               │   │   │   'task_type': 'CAUSAL_LM',                      │ │
│ │               │   │   │   'r': 32,                                       │ │
│ │               │   │   │   'lora_alpha': 64,                              │ │
│ │               │   │   │   'lora_dropout': 0.1,                           │ │
│ │               │   │   │   'target_modules': 'all-linear'                 │ │
│ │               │   │   },                                                 │ │
│ │               │   │   'training': {                                      │ │
│ │               │   │   │   'training_args': {                             │ │
│ │               │   │   │   │   'num_train_epochs': 1,                     │ │
│ │               │   │   │   │   'per_device_train_batch_size': 4,          │ │
│ │               │   │   │   │   'gradient_accumulation_steps': 4,          │ │
│ │               │   │   │   │   'gradient_checkpointing': True,            │ │
│ │               │   │   │   │   'optim': 'paged_adamw_32bit',              │ │
│ │               │   │   │   │   'logging_steps': 1,                        │ │
│ │               │   │   │   │   'learning_rate': 0.0002,                   │ │
│ │               │   │   │   │   'bf16': True,                              │ │
│ │               │   │   │   │   'tf32': True,                              │ │
│ │               │   │   │   │   'max_grad_norm': 0.3,                      │ │
│ │               │   │   │   │   ... +2                                     │ │
│ │               │   │   │   },                                             │ │
│ │               │   │   │   'sft_args': {'max_seq_length': 1024}           │ │
│ │               │   │   },                                                 │ │
│ │               │   │   'inference': {                                     │ │
│ │               │   │   │   'max_new_tokens': 256,                         │ │
│ │               │   │   │   'use_cache': True,                             │ │
│ │               │   │   │   'do_sample': True,                             │ │
│ │               │   │   │   'top_p': 0.9,                                  │ │
│ │               │   │   │   'temperature': 0.8                             │ │
│ │               │   │   },                                                 │ │
│ │               │   │   'qa': {                                            │ │
│ │               │   │   │   'llm_tests': [                                 │ │
│ │               │   │   │   │   'jaccard_similarity',                      │ │
│ │               │   │   │   │   'dot_product',                             │ │
│ │               │   │   │   │   'rouge_score',                             │ │
│ │               │   │   │   │   'word_overlap',                            │ │
│ │               │   │   │   │   'verb_percent',                            │ │
│ │               │   │   │   │   'adjective_percent',                       │ │
│ │               │   │   │   │   'noun_percent',                            │ │
│ │               │   │   │   │   'summary_length'                           │ │
│ │               │   │   │   ]                                              │ │
│ │               │   │   }                                                  │ │
│ │               │   }                                                      │ │
│ │               ]                                                          │ │
│ │  dir_helper = <llmtune.utils.save_utils.DirectoryHelper object at        │ │
│ │               0x00000259901554D0>                                        │ │
│ │        file = <_io.TextIOWrapper                                         │ │
│ │               name='experiment\\sHR8ns\\config\\config.yml' mode='r'     │ │
│ │               encoding='cp1252'>                                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│ C:\ProgramData\anaconda3\envs\llm_tkit\Lib\site-packages\llmtune\cli\toolkit │
│ .py:84 in run_one_experiment                                                 │
│                                                                              │
│    81 │   results_file_path = dir_helper.save_paths.results_file             │
│    82 │   if not results_file_path.exists():                                 │
│    83 │   │   inference_runner = LoRAInference(test, test_column, config, di │
│ ❱  84 │   │   inference_runner.infer_all()                                   │
│    85 │   │   RichUI.after_inference(results_path)                           │
│    86 │   else:                                                              │
│    87 │   │   RichUI.results_found(results_path)                             │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │                 _ = ['instruction', 'input']                             │ │
│ │            config = Config(                                              │ │
│ │                     │   save_dir='./experiment/',                        │ │
│ │                     │   ablation=AblationConfig(                         │ │
│ │                     │   │   use_ablate=False,                            │ │
│ │                     │   │   study_name='ablation'                        │ │
│ │                     │   ),                                               │ │
│ │                     │   data=DataConfig(                                 │ │
│ │                     │   │   file_type='huggingface',                     │ │
│ │                     │   │   path='yahma/alpaca-cleaned',                 │ │
│ │                     │   │   prompt='Below is an instruction that         │ │
│ │                     describes a task.  Write a response that             │ │
│ │                     appropriat'+89,                                      │ │
│ │                     │   │   prompt_stub='{output}',                      │ │
│ │                     │   │   train_size=500,                              │ │
│ │                     │   │   test_size=25,                                │ │
│ │                     │   │   train_test_split_seed=42                     │ │
│ │                     │   ),                                               │ │
│ │                     │   model=ModelConfig(                               │ │
│ │                     │   │   hf_model_ckpt='facebook/opt-125m',           │ │
│ │                     │   │   device_map='auto',                           │ │
│ │                     │   │   torch_dtype='bfloat16',                      │ │
│ │                     │   │   attn_implementation=None,                    │ │
│ │                     │   │   quantize=True,                               │ │
│ │                     │   │   bitsandbytes=BitsAndBytesConfig(             │ │
│ │                     │   │   │   load_in_8bit=False,                      │ │
│ │                     │   │   │   llm_int8_threshold=6.0,                  │ │
│ │                     │   │   │   llm_int8_skip_modules=None,              │ │
│ │                     │   │   │   llm_int8_enable_fp32_cpu_offload=False,  │ │
│ │                     │   │   │   llm_int8_has_fp16_weight=False,          │ │
│ ���                     │   │   │   load_in_4bit=True,                       │ │
│ │                     │   │   │   bnb_4bit_compute_dtype='bfloat16',       │ │
│ │                     │   │   │   bnb_4bit_quant_type='nf4',               │ │
│ │                     │   │   │   bnb_4bit_use_double_quant=True           │ │
│ │                     │   │   )                                            │ │
│ │                     │   ),                                               │ │
│ │                     │   lora=LoraConfig(                                 │ │
│ │                     │   │   r=32,                                        │ │
│ │                     │   │   task_type='CAUSAL_LM',                       │ │
│ │                     │   │   lora_alpha=64,                               │ │
│ │                     │   │   bias='none',                                 │ │
│ │                     │   │   lora_dropout=0.1,                            │ │
│ │                     │   │   target_modules='all-linear',                 │ │
│ │                     │   │   fan_in_fan_out=False,                        │ │
│ │                     │   │   modules_to_save=None,                        │ │
│ │                     │   │   layers_to_transform=None,                    │ │
│ │                     │   │   layers_pattern=None                          │ │
│ │                     │   ),                                               │ │
│ │                     │   training=TrainingConfig(                         │ │
│ │                     │   │   training_args=TrainingArgs(                  │ │
│ │                     │   │   │   num_train_epochs=1,                      │ │
│ │                     │   │   │   per_device_train_batch_size=4,           │ │
│ │                     │   │   │   gradient_accumulation_steps=4,           │ │
│ │                     │   │   │   gradient_checkpointing=True,             │ │
│ │                     │   │   │   optim='paged_adamw_32bit',               │ │
│ │                     │   │   │   logging_steps=1,                         │ │
│ │                     │   │   │   learning_rate=0.0002,                    │ │
│ │                     │   │   │   bf16=True,                               │ │
│ │                     │   │   │   tf32=True,                               │ │
│ │                     │   │   │   fp16=False,                              │ │
│ │                     │   │   │   max_grad_norm=0.3,                       │ │
│ │                     │   │   │   warmup_ratio=0.03,                       │ │
│ │                     │   │   │   lr_scheduler_type='constant',            │ │
│ │                     │   │   │   save_steps=500                           │ │
│ │                     │   │   ),                                           │ │
│ │                     │   │   sft_args=SftArgs(                            │ │
│ │                     │   │   │   max_seq_length=1024,                     │ │
│ │                     │   │   │   neftune_noise_alpha=None                 │ │
│ │                     │   │   )                                            │ │
│ │                     │   ),                                               │ │
│ │                     │   inference=InferenceConfig(                       │ │
│ │                     │   │   max_length=None,                             │ │
│ │                     │   │   max_new_tokens=256,                          │ │
│ │                     │   │   min_length=0,                                │ │
│ │                     │   │   min_new_tokens=None,                         │ │
│ │                     │   │   early_stopping=False,                        │ │
│ │                     │   │   max_time=None,                               │ │
│ │                     │   │   do_sample=True,                              │ │
│ │                     │   │   num_beams=1,                                 │ │
│ │                     │   │   num_beam_groups=1,                           │ │
│ │                     │   │   penalty_alpha=None,                          │ │
│ │                     │   │   use_cache=True,                              │ │
│ │                     │   │   temperature=0.8,                             │ │
│ │                     │   │   top_k=50,                                    │ │
│ │                     │   │   top_p=0.9,                                   │ │
│ │                     │   │   typical_p=1.0,                               │ │
│ │                     │   │   epsilon_cutoff=0.0,                          │ │
│ │                     │   │   eta_cutoff=0.0,                              │ │
│ │                     │   │   diversity_penalty=0.0,                       │ │
│ │                     │   │   repetition_penalty=1.0,                      │ │
│ │                     │   │   encoder_repetition_penalty=1.0,              │ │
│ │                     │   │   length_penalty=1.0,                          │ │
│ │                     │   │   no_repeat_ngram_size=0,                      │ │
│ │                     │   │   bad_words_ids=None,                          │ │
│ │                     │   │   force_words_ids=None,                        │ │
│ │                     │   │   renormalize_logits=False                     │ │
│ │                     │   ),                                               │ │
│ │                     │   qa=QaConfig(                                     │ │
│ │                     │   │   llm_tests=[                                  │ │
│ │                     │   │   │   'jaccard_similarity',                    │ │
│ │                     │   │   │   'dot_product',                           │ │
│ │                     │   │   │   'rouge_score',                           │ │
│ │                     │   │   │   'word_overlap',                          │ │
│ │                     │   │   │   'verb_percent',                          │ │
│ │                     │   │   │   'adjective_percent',                     │ │
│ │                     │   │   │   'noun_percent',                          │ │
│ │                     │   │   │   'summary_length'                         │ │
│ │                     │   │   ]                                            │ │
│ │                     │   )                                                │ │
│ │                     )                                                    │ │
│ │       config_path = './config.yml'                                       │ │
│ │ dataset_generator = <llmtune.data.dataset_generator.DatasetGenerator     │ │
│ │                     object at 0x00000259FF8B8750>                        │ │
│ │      dataset_path = WindowsPath('experiment/sHR8ns/dataset')             │ │
│ │        dir_helper = <llmtune.utils.save_utils.DirectoryHelper object at  │ │
│ │                     0x000002599017BE90>                                  │ │
│ │         finetuner = <llmtune.finetune.lora.LoRAFinetune object at        │ │
│ │                     0x000002598EED0310>                                  │ │
│ │  inference_runner = <llmtune.inference.lora.LoRAInference object at      │ │
│ │                     0x000002598FFD99D0>                                  │ │
│ │ results_file_path = WindowsPath('experiment/sHR8ns/results/results.csv') │ │
│ │      results_path = WindowsPath('experiment/sHR8ns/results')             │ │
│ │              test = Dataset({                                            │ │
│ │                     │   features: ['output', 'input', 'instruction',     │ │
│ │                     'formatted_prompt'],                                 │ │
│ │                     │   num_rows: 25                                     │ │
│ │                     })                                                   │ │
│ │       test_column = 'output'                                             │ │
│ │             train = Dataset({                                            │ │
│ │                     │   features: ['output', 'input', 'instruction',     │ │
│ │                     'formatted_prompt'],                                 │ │
│ │                     │   num_rows: 500                                    │ │
│ │                     })                                                   │ │
│ │      weights_path = WindowsPath('experiment/sHR8ns/weights')             │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│ C:\ProgramData\anaconda3\envs\llm_tkit\Lib\site-packages\llmtune\inference\l │
│ ora.py:80 in infer_all                                                       │
│                                                                              │
│    77 │   │   │   writer = csv.writer(f)                                     │
│    78 │   │   │   writer.writerow(header)                                    │
│    79 │   │   │   for row in results:                                        │
│ ❱  80 │   │   │   │   writer.writerow(row)                                   │
│    81 │                                                                      │
│    82 │   def infer_one(self, prompt: str) -> str:                           │
│    83 │   │   input_ids = self.tokenizer(prompt, return_tensors="pt", trunca │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │       f = <_io.TextIOWrapper                                             │ │
│ │           name='experiment\\sHR8ns\\results\\results.csv' mode='w'       │ │
│ │           encoding='cp1252'>                                             │ │
│ │  header = ['Prompt', 'Ground Truth', 'Predicted']                        │ │
│ │     idx = 24                                                             │ │
│ │   label = 'The language of the text "Buonasera, il mio nome e Giuseppe"  │ │
│ │           is Italian.'                                                   │ │
│ │  labels = [                                                              │ │
│ │           │   'Early, she left the party.',                              │ │
│ │           │   'We solve the equation f(x) = 0 on the domains x ≤ 1 and x │ │
│ │           > 1.\n\nIf x ≤ 1, then f'+261,                                 │ │
│ │           │   "Warm breeze on my face\nEndless sun brings joy and        │ │
│ │           peace\nSummer, please don't fad"+1,                            │ │
│ │           │   'Here are several methods to improve the accuracy of       │ │
│ │           machine learning models:\n\n1.'+1416,                          │ │
│ │           │   'Global warming can be reversed by reducing greenhouse gas │ │
│ │           emissions and deforest'+6,                                     │ │
│ │           │   'Putting the pieces of a puzzle together is like crafting  │ │
│ │           a well-written piece. J'+349,                                  │ │
│ │           │   'We can solve for x by using algebraic operations to       │ │
│ │           isolate the variable on one '+340,                             │ │
│ │           │   '1. "We all make mistakes,"\n2. "but",\n3. "learning from  │ │
│ │           them is important."',                                          │ │
│ │           │   '1. Brazil\n2. Argentina\n3. Colombia\n4. Chile',          │ │
│ │           │   'Based on the given nutritional information, the food item │ │
│ │           can be classified as a'+72,                                    │ │
│ │           │   ... +15                                                    │ │
│ │           ]                                                              │ │
│ │  prompt = 'Below is an instruction that describes a task.  Write a       │ │
│ │           response that appropriat'+139                                  │ │
│ │ prompts = [                                                              │ │
│ │           │   'Below is an instruction that describes a task.  Write a   │ │
│ │           response that appropriat'+164,                                 │ │
│ │           │   'Below is an instruction that describes a task.  Write a   │ │
│ │           response that appropriat'+175,                                 │ │
│ │           │   'Below is an instruction that describes a task.  Write a   │ │
│ │           response that appropriat'+109,                                 │ │
│ │           │   'Below is an instruction that describes a task.  Write a   │ │
│ │           response that appropriat'+145,                                 │ │
│ │           │   'Below is an instruction that describes a task.  Write a   │ │
│ │           response that appropriat'+180,                                 │ │
│ │           │   'Below is an instruction that describes a task.  Write a   │ │
│ │           response that appropriat'+124,                                 │ │
│ │           │   'Below is an instruction that describes a task.  Write a   │ │
│ │           response that appropriat'+107,                                 │ │
│ │           │   'Below is an instruction that describes a task.  Write a   │ │
│ │           response that appropriat'+174,                                 │ │
│ │           │   'Below is an instruction that describes a task.  Write a   │ │
│ │           response that appropriat'+114,                                 │ │
│ │           │   'Below is an instruction that describes a task.  Write a   │ │
│ │           response that appropriat'+184,                                 │ │
│ │           │   ... +15                                                    │ │
│ │           ]                                                              │ │
│ │  result = '  ### Output:  ### Input:  ### Output:  ### Input:  ###       │ │
│ │           Input:  ### Output:  ###'+749                                  │ │
│ │ results = [                                                              │ │
│ │           │   (                                                          │ │
│ │           │   │   'Below is an instruction that describes a task.  Write │ │
│ │           a response that appropriat'+164,                               │ │
│ │           │   │   'Early, she left the party.',                          │ │
│ │           │   │   ' You left the party early\n> ### Input: She left the  │ │
│ │           party early   > ### Output: '+147                              │ │
│ │           │   ),                                                         │ │
│ │           │   (                                                          │ │
│ │           │   │   'Below is an instruction that describes a task.  Write │ │
│ │           a response that appropriat'+175,                               │ │
│ │           │   │   'We solve the equation f(x) = 0 on the domains x ≤ 1   │ │
│ │           and x > 1.\n\nIf x ≤ 1, then f'+261,                           │ │
│ │           │   │   ' * 1\n\nThat’s a good idea.  If you’ve got a lot of   │ │
│ │           time, you can try to solve thi'+876                            │ │
│ │           │   ),                                                         │ │
│ │           │   (                                                          │ │
│ │           │   │   'Below is an instruction that describes a task.  Write │ │
│ │           a response that appropriat'+109,                               │ │
│ │           │   │   "Warm breeze on my face\nEndless sun brings joy and    │ │
│ │           peace\nSummer, please don't fad"+1,                            │ │
│ │           │   │   '  ### Input: ### Output: ### Input: ### Output: ###   │ │
│ │           Output: ### Output: ### Inpu'+938                              │ │
│ │           │   ),                                                         │ │
│ │           │   (                                                          │ │
│ │           │   │   'Below is an instruction that describes a task.  Write │ │
│ │           a response that appropriat'+145,                               │ │
│ │           │   │   'Here are several methods to improve the accuracy of   │ │
│ │           machine learning models:\n\n1.'+1416,                          │ │
│ │           │   │   '  ### Input:  ### Output:  ### Input:  ### Output:    │ │
│ │           ### Input:  ### Output:  ###'+954                              │ │
│ │           │   ),                                                         │ │
│ │           │   (                                                          │ │
│ │           │   │   'Below is an instruction that describes a task.  Write │ │
│ │           a response that appropriat'+180,                               │ │
│ │           │   │   'Global warming can be reversed by reducing greenhouse │ │
│ │           gas emissions and deforest'+6,                                 │ │
│ │           │   │   ' ________  ###  ###  ###  ###  ###  ###  ###\n\nBelow │ │
│ │           is an instruction that descr'+657                              │ │
│ │           │   ),                                                         │ │
│ │           │   (                                                          │ │
│ │           │   │   'Below is an instruction that describes a task.  Write │ │
│ │           a response that appropriat'+124,                               │ │
│ │           │   │   'Putting the pieces of a puzzle together is like       │ │
│ │           crafting a well-written piece. J'+349,                         │ │
│ │           │   │   ' You need to be a certain type of person ###          │ │
│ │           Character: Do you have a good idea '+1100                      │ │
│ │           │   ),                                                         │ │
│ │           │   (                                                          │ │
│ │           │   │   'Below is an instruction that describes a task.  Write │ │
│ │           a response that appropriat'+107,                               │ │
│ │           │   │   'We can solve for x by using algebraic operations to   │ │
│ │           isolate the variable on one '+340,                             │ │
│ │           │   │   '  ### Input:  ### Output:  ### Output:  ### Input:    │ │
│ │           ### Output:  ### Input:  ###'+744                              │ │
│ │           │   ),                                                         │ │
│ │           │   (                                                          │ │
│ │           │   │   'Below is an instruction that describes a task.  Write │ │
│ │           a response that appropriat'+174,                               │ │
│ │           │   │   '1. "We all make mistakes,"\n2. "but",\n3. "learning   │ │
│ │           from them is important."',                                     │ │
│ │           │   │   " We don't have the answers. ### Results: Our mistakes │ │
│ │           do not make us lazy, but i"+130                                │ │
│ │           │   ),                                                         │ │
│ │           │   (                                                          │ │
│ │           │   │   'Below is an instruction that describes a task.  Write │ │
│ │           a response that appropriat'+114,                               │ │
│ │           │   │   '1. Brazil\n2. Argentina\n3. Colombia\n4. Chile',      │ │
│ │           │   │   '  ###   * Requested by:  ###  * Requested by:  ###  * │ │
│ │           Requested by:  ###  ###  #'+733                                │ │
│ │           │   ),                                                         │ │
│ │           │   (                                                          │ │
│ │           │   │   'Below is an instruction that describes a task.  Write │ │
│ │           a response that appropriat'+184,                               │ │
│ │           │   │   'Based on the given nutritional information, the food  │ │
│ │           item can be classified as a'+72,                               ��� │
│ │           │   │   ' Calories: 1,843 | Protein: 1g ### Input: Calories:   │ │
│ │           11,731 | Protein: 1g ### Out'+1077                             │ │
│ │           │   ),                                                         │ │
│ │           │   ... +15                                                    │ │
│ │           ]                                                              │ │
│ │     row = (                                                              │ │
│ │           │   'Below is an instruction that describes a task.  Write a   │ │
│ │           response that appropriat'+175,                                 │ │
│ │           │   'We solve the equation f(x) = 0 on the domains x ≤ 1 and x │ │
│ │           > 1.\n\nIf x ≤ 1, then f'+261,                                 │ │
│ │           │   ' * 1\n\nThat’s a good idea.  If you’ve got a lot of time, │ │
│ │           you can try to solve thi'+876                                  │ │
│ │           )                                                              │ │
│ │    self = <llmtune.inference.lora.LoRAInference object at                │ │
│ │           0x000002598FFD99D0>                                            │ │
│ │  writer = <_csv.writer object at 0x00000259901B3100>                     │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│ C:\ProgramData\anaconda3\envs\llm_tkit\Lib\encodings\cp1252.py:19 in encode  │
│                                                                              │
│    16                                                                        │
│    17 class IncrementalEncoder(codecs.IncrementalEncoder):                   │
│    18 │   def encode(self, input, final=False):                              │
│ ❱  19 │   │   return codecs.charmap_encode(input,self.errors,encoding_table) │
│    20                                                                        │
│    21 class IncrementalDecoder(codecs.IncrementalDecoder):                   │
│    22 │   def decode(self, input, final=False):                              │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │ final = False                                                            │ │
│ │ input = '"Below is an instruction that describes a task.  Write a        │ │
│ │         response that appropria'+1482                                    │ │
│ │  self = <encodings.cp1252.IncrementalEncoder object at                   │ │
│ │         0x0000025990187AD0>                                              │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────╯
UnicodeEncodeError: 'charmap' codec can't encode character '\u2264' in position
154: character maps to <undefined>

**Comment by benjaminye** [comment]
Hi @jeetendraabvv do you know what terminal are you using? I would suggest using [Windows Terminal](https://github.com/microsoft/terminal).

In any case, our tests are run on Linux and Windows, although supported, is not well tested. I would suggest checking out [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) for running this toolkit.

**Comment by benjaminye** [comment]
Closed due to inactivity. Please feel free to reopen this issue if assistance is still required.
