### ISSUE TITLE
bitsandbytes version pinned to out of date release

### ISSUE THREAD

**Issue by Titus-von-Koeller** [georgian-io/LLM-Finetuning-Toolkit#189]
Hi all,

a `bitsandbytes` maintainer here :)

I see you have a nice integration with bitsandbytes, really cool!

Due to an issue on our repo I became aware that some users can't use bitsandbytes with your project as it's pinned to an [out of date version of BNB](https://github.com/georgian-io/LLM-Finetuning-Toolkit/blob/e440a9d8ef6ff935c91841f36dec27182480ae8b/pyproject.toml#L44).

Is there anything we can help with that's keeping you from upgrading?

`0.43` introduced Windows support [which this user of your library needs](https://github.com/bitsandbytes-foundation/bitsandbytes/issues/1131#issuecomment-2132225193) and the current patch release `0.43.3` fixed a very significant issue with QLoRA that leads to immense memory reductions for larger context and batch sizes.

With this new patch release, for each sequence (i.e. batch size increase of one) we expect memory savings of:
- 405B: 39GB for `seqlen=1024`, and 4888GB for `seqlen=128,00`
- 70B: 10.1GB for `seqlen=1024` and  1258GB for `seqlen=128,00`

This was due to activations being unnecessary for frozen parameters, yet the memory for them was still erroneously allocated due to the now fixed bug.

**Comment by benjaminye** [comment]
Thank you @Titus-von-Koeller for the fixes and the PR - you rock! 😃
This explains how I always run out of memory for long context! 😅

I'll have it merged ASAP!
